import React from "react";
import './vision.component.scss';
import ugly_5 from '../assets/img/ugly-1.png';

// Vision & Rarity
const VisionAndRarity = (props: any) => {
  return (
    <div id="ugly-vision" className="main-view_page4">
      <div className="div-description">
        <div className="div-vision">
          <p className="txt-caption">OUR VISION</p>
          <p className="txt-description">
            Our team is passionate about creating an amazing community with purpose, offering holders exciting opportunities.<br/> 
            The interests of our community are extremely valuable to us, which is why we want YOU to have a say.<br/> 
            Holders will be regularly able to vote for roadmap ideas to determine the next direction for 231 Uglies.<br/> 
            There will be various options such as staking, creation of mutated Uglies and many more.<br/> 
            The community will also decide which charity will receive our 10 ETH donation.<br/> 
            We are 231 Uglies and you will be heard!
          </p>
        </div>
        <div className="div-rarity">
          <p className="txt-caption">RARITY</p>
          <p className="txt-description">
            231 Uglies are generated by combining more than 120 unique hand drawn traits, with different rarities among the categories.<br/> 
            Each species has its own special traits, which the other two don't.<br/>
            After you mint your Uglies, they're completely yours for both personal and commercial use. <br/>
            But we think you will want to keep these forever.
          </p>
        </div>
      </div>
    </div>
  );
}

export default VisionAndRarity;